### ISSUE TITLE
Update to Kibana 4

### ISSUE THREAD

**Issue by kikicarbonell** [tabolario/kibana-rack#18]
Update to Kibana 4

**Comment by tabolario** [comment]
Unfortunately the operating mode of Kibana 4 is a standalone binary now, so if you wanted to run it with a Rails application for the purposes of authentication/authorization, the best way to do it IMO would be to use something like jaswope/rack-reverse-proxy in tandem with whatever auth/authz you're using in the Rails app. I'll be continuing to maintain kibana-rack for Kibana 3.
